### PR TITLE
New caption for omc messages

### PR DESCRIPTION
**Pull request by lochel**
Messages may be just warnings, so it is really strange to entitle them with "OMC-ERROR".

### CODE REVIEW

**Comment by hkiel** [comment]
Would it be good to parse the messages and put a proper text ("OMC-ERROR", "OMC-WARNING", "OMC-MESSAGE") or even set the background color of the cell to light-red for error, light-yellow for warning and otherwise leave it light grey?

**Comment by lochel** [comment]
@hkiel Yes, that would be much better. Can you do that?

**Comment by hkiel** [comment]
@lochel I can do this.

Concerning usablility: messages contain the line number of the corresponding code, but there is no line number visible in the text box, so the user has to count the lines to find the correct place. Would be nice to have the possibility to show line numbers in the editor.

**Comment by hkiel** [comment]
@lochel I implemented the coloring, but it is not saved to the notebook, so at reloading the notebook the cells are white again, but I guess that should be okay?

**Comment by lochel** [comment]
I think that is fine for now.

**Pull request closed without merging**
