### PR TITLE
Export Notebook as PDF

### PR DESCRIPTION
**Pull request by hkiel**

### CODE REVIEW

**Comment by sjoelund** [comment]
Yes, but please don't use the GitHub GUI to merge pull requests in the future. Use the rebase feature instead.
You could also create a pull request on OpenModelica.git to update the maintenance/v1.11 branch OMNotebook submodule to the new hash (https://github.com/OpenModelica/OpenModelica/pull/24).

**Comment by hkiel** [comment]
Sorry for the GUI merge. I also find it very clumsy.
Do you have the necessary shell commands for the rease at hand?

**Comment by sjoelund** [comment]
The GitHub GUI can perform a rebase. It's only the default that is a merge. Otherwise, pushing without a pull request is similar to the rebase...
On Dec 6, 2016 10:01, Henning Kiel <notifications@github.com> wrote:Sorry for the GUI merge. I also find it very clumsy.
Do you have the necessary shell commands for the rease at hand?

**Comment by lochel** [comment]
@sjoelund One can disable the merge functionality within the github repository settings (see settings -> options -> merge button).

**Comment by sjoelund** [comment]
That's a useful new feature (just like the ability to rebase instead of merge...)

**Pull request merged**
