### PR TITLE
Fix windows makefile such that OMNotebook is built again

### PR DESCRIPTION
**Pull request by hkiel**

### CODE REVIEW

**Comment by hkiel** [comment]
@sjoelund @adrpo Can you trigger a new Windows nightly with this PR? I would like to test my OMNotebook changes. Unfortunately I messed up the Makefile such that OMNotebook was no longer built. I hopefully fixed that.
My changes are fine on macOS and I would like to see them in v1.11beta2

**Comment by adeas31** [comment]
I started the windows nightly builds.

**Comment by adrpo** [comment]
Some adaptation is needed on Windows to generate omc_config.h, I'm trying to fix this.

**Comment by adrpo** [comment]
Should be solved with PR #20.

**Pull request merged**
