### PR TITLE
New caption for omc messages

### PR DESCRIPTION
**Pull request by hkiel**
also highlight error cells in red, warning cells in yellow

### CODE REVIEW

**Comment by hkiel** [comment]
As discussed in #38 I added light red background for cells with "Error:" and light yellow background for cells with "Warning:"

**Review by lochel — COMMENTED** [review]
I didn't build the changes. However, it would be nice to have highlighting for each message if there is a bunch of warnings/errors in the log. Or does the changes cover that as well?

**Review by adeas31 — APPROVED** [review]
I tried the code and it looks fine.

**Comment by hkiel** [comment]
@lochel This PR only changes background color of the cell according to "worst" message.
I agree, it would be good to highlight also the "worst" messages, to find e.g. the error in a huge list of warnings. However, this is a bit more work. You can open a ticket for this.

There is also some kind of hyperlink in the output for the code location, however, clicking the link does not work. Also, from the error message (e.g.: `[<interactive>:24:3-24:14:writable] Error: ...`) OMNotebook cannot tell in which cell the offending code resides. So the links are not (yet) useful (and they are even not stored in the .onb).

**Comment by lochel** [comment]
No problem. That's fine for now 👍

**Review by lochel — APPROVED** [review]

**Comment by adeas31** [comment]
@hkiel you could use `getMessagesStringInternal` instead of `getErrorString` which gives detailed information about each error message. See how its used in OMEdit.

**Comment by hkiel** [comment]
@adeas31 `getMessagesStringInternal` does not help here, because we have an interactive session and filename is always `<interactive>`, so we cannot find out from which cell the message comes.

**Comment by adeas31** [comment]
Yeah that's right.
So should I merge this PR?

**Pull request merged**
